### ISSUE TITLE
Year 1 - Data Driven Mine Oversight

### ISSUE THREAD

**Issue by bcdevex** [bcgov/mds#2]
<p>This is a paid opportunity through the <a href="https://bcdevexchange.org">BCDevExchange</a>.</p><br/><p>To apply, visit the <a href="https://bcdevexchange.org/opportunities/swu/opp-basic-functionality-update">opportunity page</a> and submit a proposal before Wednesday, June 6, 2018</p>

**Comment by StephenOTT** [comment]
Hi you have a larger contract sum for this opportunity, so you get into more thorough review of IP ownership and control:

In the draft contract you link to on the opportunity page in section 8.5 on page 13, you state:

> Contractor’s Intellectual Property Rights
> All intellectual property rights, including copyright, in the Contributions that are not owned by third parties will be owned by the Contractor.

Given this is open source, what happens when the contractor is also the third-party?  You provide ip ownership opportunities to contributions made back to third-parties, but do not provide the same benefit for the contractor when they are also the third-party?

Thanks

**Comment by StephenOTT** [comment]
In section 8 on page 13 of the draft contract, you use `Province material` as a term.  How do you define this term.  It is more significant given the sum of the potential contract.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by ActionAnalytics** [comment]
No longer relevant

**Comment by bcdevex** [comment]
This opportunity has been assigned
