### ISSUE TITLE
Elasticsearch Dashboards for Mines

### ISSUE THREAD

**Issue by bcdevex** [bcgov/mds#513]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-elastic-search"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-elastic-search">visit the opportunity page</a>.
The opportunity closes on <b>Tuesday, February 19th, 2019 at 16:00 PST</b>.</p>

**Comment by jillcarr** [comment]
Hi All, if you have any questions feel free to post here and between myself and Julian(@ActionAnalytics) we'll make sure we get back to you as soon as possible.

**Comment by simiansim** [comment]
I am trying to understand the expected work for this project. The description might be summarized as building dashboards using Kibana? Is this corrents

**Comment by ActionAnalytics** [comment]
Thank you for taking the time to go over the opportunity and craft these questions.  Responses will be after each question as follows:

1. The description might be summarized as building dashboards using Kibana (a Web UI)? is this correct, or are you looking for a vendor to also build an ElasticSearch database as well?
**The ElasticSearch instance is up and running in the cloud.  We have existing connections from our app to this cloud instance.  We mostly require indexing and dashboard creation.**

2. Have you already accomplished having an elastic search database instance running, (software setup) or is this required?
**Yes Elastic is up and running, and the initial setup is out of scope.  The majority of the effort is expected to be directed at automating the exporting of the right data, then presenting it in an appealing and reusable manner.**

3. Also is this running (or is to be run) in a local datacenter or at a cloud provider, and which one?
**Elastic is currently running at a Cloud provider for this opportunity.**

4. is an index in elastic search designed and built (data design and loading) or is this required?
**Index creation will be required.**

5. Fixed price contracts should never have undefined scope: what are the additional dashboards required?
**We wish the contract to have open ended dashboard design in some areas in order to promote creativity on the part of the vendor.**

6. in reference to section 4) Automation of updates, are you talking about the data loading integration into ElasticSearch, ...or the delivery of data from ElasticSearch to the visible dashboard in  a web browser?
**Both.  The MDS application will need to some modifications by the vendor in order to selectively package data over to the cloud ElasticSearch instance.  We also wish the dashboards themselves to show up to date information.**

We hope that this answers your questions.  Let us know if anything else comes up.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by jillcarr** [comment]
We received 2 proposals and Jonathan Laplante was the successful candidate - Jonathan Laplante @jlaplante333 - for feedback please contact jillian.carruthers@gov.bc.ca

**Comment by mark-a-wilson** [comment]
Hey guys (:BCDevExchange hat on:) — just to confirm: was this work completed and paid?

**Comment by jillcarr** [comment]
correct

Jillian Carruthers, mba, pmp
Director, Digital Services (EAO & Mines)
MOBILE: 250-216-8493
